# Generated by Django 4.2.18 on 2025-04-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه فاکتور')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فاکتور')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('final', 'نهایی'), ('paid', 'پرداخت شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.customer', verbose_name='مشتری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آیتم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
