# Generated by Django 4.2.18 on 2025-04-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='آدرس مشتری (دستی)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مشتری (دستی)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مشتری (دستی)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی (دستی)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن مشتری (دستی)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.customer', verbose_name='مشتری'),
        ),
    ]
