# Generated by Django 4.2.18 on 2025-04-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_customer_national_code_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_full_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_national_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_phone_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.customer', verbose_name='مشتری'),
        ),
    ]
