# Generated by Django 4.2.18 on 2025-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_notes_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد'),
        ),
    ]
